### PR TITLE
update libgit2 and Objective-Git

### PR DESCRIPTION
**Pull request by keturn**
@tiennou has made some patches recently to update from old versions of Objective Git and libgit2.

### CODE REVIEW

**Comment by keturn** [comment]
When I noticed that I was using an old version of GitX this afternoon, I tried to upgrade. That turned in to a much bigger project than I expected!

I use GitX every day, so I'm glad to see some people are working on it. I didn't find any built versions for SSP's repository, though, so I tried to build it myself.

Then I ran in to build problems, and after reading a bunch of libgit2 issues, I realized I should check if I was using an up-to-date version of that, and that's when I found @tiennou's fork had updated those references.

**Comment by keturn** [comment]
I was too hasty to suggest that this be merged; I don't think it builds yet.

**Comment by tiennou** [comment]
`git submodule update --init --recursive` is your friend. Or alternatively, `git config --global alias.subup "submodule update --init --recursive"` :wink:.

**Comment by ssp** [comment]
Hey @keturn,

unfortunately I must have overlooked your note when you made it. When revisiting the project now I noticed that @tiennou has made numerous patches since and I merged them into my branch.

**Pull request closed without merging**
